# source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'WebRTC-Demo' do
    use_frameworks!
    pod 'Starscream'
    pod 'GoogleWebRTC', '~> 1.1'
    pod 'CocoaAsyncSocket'
    pod 'HandyJSON'
    pod 'Socket.IO-Client-Swift', '~> 15.2.0'
end
